/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface ImageText {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLImageTextElement extends Components.ImageText, HTMLStencilElement {
    }
    var HTMLImageTextElement: {
        prototype: HTMLImageTextElement;
        new (): HTMLImageTextElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "image-text": HTMLImageTextElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ImageText {
        "onToggle"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "image-text": ImageText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "image-text": LocalJSX.ImageText & JSXBase.HTMLAttributes<HTMLImageTextElement>;
        }
    }
}
